name: ESLint

on:
  push:
    branches:
      - master
      - development
  pull_request:
    branches:
      - '**'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          corepack enable
          corepack prepare pnpm@9.12.1 --activate
          pnpm install

      - name: Run ESLint
        run: pnpm eslint .
